#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2011-07-20
#describe: 读取密码
stty -echo
read -p "PASS:" pass
stty echo
echo
echo $pass
#printf "\n%s\n" "$pass"

#exit 0

printf "Enter new password:"
stty -echo
read pass < /dev/tty
printf "\n"
printf "Enter again:"
read pass2 < /dev/tty
printf "\n"
stty echo
echo $pass
echo $pass2
