#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2012-01-08
#describe:字体 颜色

export BLACK="\033[30m"
export RED="\033[31m"
export GREEN="\033[32m"
export YELLOW="\033[33m"
export BLUE="\033[34m"
export PURPLE="\033[35m"
export CYAN="\033[36m"
export WHITE="\033[37m"

export BLACKB="\033[40m"
export REDB="\033[41m"
export GREENB="\033[42m"
export YELLOWB="\033[43m"
export BLUEB="\033[44m"
export PURPLEB="\033[45m"
export CYANB="\033[46m"
export WHITEB="\033[47m"

export NORMAL="\033[0m"
export BOLD="\033[1m"
export BOLDOFF="\033[2m"
export ITALIC="\033[3m"
export ULON="\033[4m"
export INVON="\033[7m"
