" Runtime Path Manipulation
execute pathogen#infect()

" 设置编码为utf8
set encoding=utf8
" 设置屏幕显示编码为utf8
set termencoding=utf8

" 语法高亮
syntax on
syntax enable

" 设置为增强模式，不兼容vi
set nocompatible

" 设置当前行高亮
set cursorline
" 设置高亮80列
set colorcolumn=80

" 显示行号
set number
" 显示状态
set ruler
" 显示模式提示
set showmode
" 显示底色
set bg=dark
" 设置底部状态栏
set laststatus=2

" 设置自动缩进
set autoindent 
" next level indent
set smartindent
" 设置增强型自动补全
set wildmenu
" 设置C模式缩进
" set cindent
" 设置鼠标开启
" set mouse=a

" 将TAB键转换为4个空格
set expandtab
" set noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" 查找高亮显示
set hlsearch
" 在输入字符窜时就开始查找
set incsearch
"查找字符窜时忽略大小写
set ignorecase

" 设置折叠栏启用
set foldenable
" 设置折叠栏宽度
set foldcolumn=0
" 设置折叠层数
set foldnestmax=3
" 设置格式化折叠
" set foldmethod=indent

" 设置屏幕为256色
set t_Co=256
" 设置自动补全颜色
hi Pmenu ctermbg=black ctermfg=white
hi PmenuSel ctermbg=red ctermfg=white
" 设置折叠颜色
hi Folded ctermfg=241 ctermbg=NONE
" 设置搜索高亮的颜色
hi Search ctermfg=0
" 当前行背景色高亮
hi CursorLine cterm=NONE ctermbg=black ctermfg=NONE guibg=black guifg=NONE

" 自动补全{}
" inoremap { {}<LEFT>
" 自动补全[]
" inoremap [ []<LEFT>
" 自动补全()
" inoremap ( ()<LEFT>
" 自动补全""
" inoremap " ""<LEFT>
" 自动补全''
" inoremap ' ''<LEFT>

" 用CTRL-H向左切换tab
nmap  gT
imap  <ESC>gT
" 用CTRL-L向右切换tab
nmap  gt
imap  <ESC>gt

" 用SHIFT-H向左切换分屏
nmap H h
" 用SHIFT-J向下切换分屏
nmap J j
" 用SHIFT-K向上切换分屏
nmap K k
" 用SHIFT-L向右切换分屏
nmap L l

" 用F5将在光标当前行进行折叠
" nnoremap <F5> zc
" 用F6展开光标当前行的折叠
" nnoremap <F6> zo
" 用F7全部折叠
nnoremap <F7> zM
" 用F8展开全部折叠
nnoremap <F8> zR
" 用SHIFT+Z切换折叠状态
nmap Z za

" 按F5自动使用Makefile编译
nnoremap <F5> :make clean;make<CR>

" NERDTree {
let NERDTreeWinSize=30
let NERDTreeWinPos='right'
let NERDTreeShowHidden=0
nnoremap <F4> :NERDTreeToggle<CR>
" }

" powerline {
let g:Powerline_symbols='fancy'
" }

" a.vim {
nnoremap <F10> :AS<CR><C-W>5+
nnoremap <F11> :AS<CR><C-W>5-
" }

" taglist {
" 启动vim后自动打开taglist窗口
let Tlist_Auto_Open=1
" 在窗口左侧显示taglist窗口
let Tlist_Use_Left_Window=1
let Tlist_WinWidth=30
" 不同时显示多个文件的tag，只显示当前文件的
let Tlist_Show_One_File=1
" taglist只显示当前文件tag，其它文件的tag折叠
let Tlist_File_Fold_Auto_Close=1
" 如果taglist窗口是最后一个窗口，则退出vim
let Tlist_Exit_OnlyWindow=1
" 选择tag后关闭taglist窗口
" let Tlist_Close_On_Select=1
" 显示或关闭代码目录
nnoremap <silent> <F9> :TlistToggle<CR>
" }

" for python {
autocmd FileType python call PythonSetting()
function PythonSetting()
	setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4
	let g:indent_guides_auto_colors = 0
	let g:indent_guides_guide_size = 1
	let g:indent_guides_start_level = 2
	let g:indent_guides_enable_on_vim_startup = 1
	autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=darkgrey
	autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=grey
	IndentGuidesEnable
	" for pydiction {
	let g:pydiction_location = '~/.vim/bundle/pydiction/complete-dict'
	" }
endfunction
" }

" for html {
autocmd FileType html call HTMLSetting()
autocmd FileType xml call HTMLSetting()
function HTMLSetting()
	" 自动补全<>
	" inoremap < <><LEFT>
endfunction
" }

" for solarized {
set background=dark
let g:solarized_termcolors = 256
let g:solarized_termtrans = 1
colorscheme solarized
"}

" 自动保存视图
" au BufWinLeave * silent mkview
" 自动加载视图
" au BufWinEnter * silent loadview
