#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2011-07-23
#describe:

if [ $# -eq 0 ];then
	echo "Please input project name"
	return 0
fi
mkdir -p "$1/src"
webRoot="$1/WebRoot"
mkdir -p "$webRoot"
mkdir -p "$webRoot/META-INF"
webINF="$webRoot/WEB-INF"
mkdir -p "$webINF"
mkdir -p "$webINF/lib"
mkdir -p "$webINF/classes"

file_jsp index -n
mv index.jsp "$webRoot"

file_xml_web "$1"
mv web.xml "$webINF"
