#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2011-07-23
#describe:

if [ $# -eq 0 ];then
	echo "[html]Please input file name"
	exit 0
fi

title="$1"
file="$title.html"
cat > "$file" << EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<!--
	Auther:   $(whoami)
	Date:     $(date +%Y-%m-%d)
	Email:    ${email}
    Home:     ${home_page}
	Describe:
	-->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>${title}</title>
	<!--
	<link rel="stylesheet" type="text/css" href="${title}.css">
	<script type="text/javascript" src="jquery.js"></script>
	<script type="text/javascript" src="${title}.js"></script>
	-->
</head>
<body>
<h1>${title}</h1>
</body>
</html>
EOF

if [ "$2" != "-n" ];then
	vi "$file"
fi
