#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2012-02-02
#describe:new file of python

file="$1.py"
cat > "$file" <<EOF
#!/usr/bin/env python
#encoding:utf-8
# Author:   $(whoami)
# Date:     $(date +%Y-%m-%d)
# Email:    $email
# Home:     $home_page
# Vim:      tabstop=4 shiftwidth=4 softtabstop=4
# Describe:

EOF
chmod a+x "$file"

if [ "$2" != "-n" ];then
	vi "$file"
fi
