#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2011-07-23
#describe:

if [ $# -eq 0 ];then
	file="struts.xml"
else
	file="$1.xml"
fi

cat > "$file" << EOF
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE struts PUBLIC "-//Apache Software Foundation//DTD Struts Configuration 2.1//EN" "http://struts.apache.org/dtds/struts-2.1.dtd">
<struts>
	<!--
	<include file="file.xml"/>
	-->
	<package name="default" extends="struts-default" namespace="/">
		<global-results>
			<result name="error" type="redirectAction">error</result>
		</global-results>
		<global-exception-mappings>
			<exception-mapping result="error" exception="java.lang.Exception"></exception-mapping>
		</global-exception-mappings>
		<action name="error">
			<result>/error.jsp</result>
		</action>
	</package>
</struts>
EOF

if [ "$2" != "-no" ];then
	vi "$file"
fi
