#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2012-01-09
#describe:redmine

if [ "$(dpkg -l | grep redmine)" == '' ];then
	read -p "install redmine?[y/n]" input
	if [ $input == 'y' ] || [ $input == 'Y' ];then
		while [ "$(dpkg -l | grep mysql-server)" == '' ]
		do
			install-mysql
		done
		while [ "$(dpkg -l | grep apache2)" == '' ]
		do
			install-apache
		done
		sudo add-apt-repository ppa:ondrej/redmine
		sudo apt-get update
		sudo apt-get install redmine redmine-mysql libapache2-mod-passenger
		sudo ln -s /usr/share/redmine/public /var/www/redmine
		sudo sed -i "3a \  PassengerDefaultUser www-data" /etc/apache2/mods-available/passenger.conf
		sudo a2enmod passenger > /dev/null 2>&1
		default=/etc/apache2/sites-available/default
		default_ssl=/etc/apache2/sites-available/default-ssl
		redmine="\n\t<Directory \/var\/www\/redmine>\n\t\tRailsBaseURI \/redmine\n\t\tPassengerResolveSymlinksInDocumentRoot on\n\t</Directory>"
		line=$(sed -n '/<\/Directory>/=' $default | head -2 | tail -1)
		sudo sed -i "${line}a\ $redmine" $default
		line=$(sed -n '/<\/Directory>/=' $default_ssl | head -2 | tail -1)
		sudo sed -i "${line}a\ $redmine" $default_ssl
		sudo /etc/init.d/apache2 restart
	fi
fi
