#!/bin/bash
#author:jhat
#email:cpf624@126.com
#date:2012-01-07
#describe:Google-Chrome

CHROME_FILE="google-chrome-stable_current_amd64.deb"
CHROME_URL="https://dl.google.com/linux/direct/${CHROME_FILE}"

if [ "$(dpkg -l | grep google-chrome-stable)" == '' ];then
	read -p "install google-chrome?[y/n]" input
	if [ $input == 'y' ] || [ $input == 'Y' ];then
	    if [ ! -f "$CHROME_FILE" ]; then
            wget -N "$CHROME_URL"
	        sudo dpkg -i "$CHROME_FILE"
	    fi
    fi
fi
